[theme]
# Set the base theme to dark so white accents are visible
base="dark"

# Set the primary accent color to white
primaryColor="#FFFFFF"

# Optional: Further customize colors for better contrast
backgroundColor="#000000"
textColor="#FFFFFF"